### ISSUE TITLE
Error Bang nhpdf. 

### ISSUE THREAD

**Issue by ThisMe124** [LitRHap/wabot#1]
/node_modules/pdfkit/js/pdfkit.js:4445
      throw new Error('Unknown image format.');
            ^

Error: Unknown image format.

Errornya Kek Gini Kadang Kadang Bang  jadi Botnya Selalu Crash kalau ada error gitu :(

**Comment by unknowkzr** [comment]
Apus filenya entar ga eror lagi

**Comment by ThisMe124** [comment]
Udah bisa bang

**Comment by ThisMe124** [comment]
Thanks info nya :D

**Comment by ThisMe124** [comment]
Bye Mau Close Issue Dulu :D

**Comment by ThisMe124** [comment]
GOODBYE ~~~~~

**Comment by FarhanssAja** [comment]
Waduh telat sebulan
