### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peraaxd** [LitRHap/wabot#8]
Fitur .ig error bang

**Comment by LitRHap** [comment]
apinya emror banh

**Comment by peraaxd** [comment]
> apinya emror banh

Waduh

**Comment by Ervan2525** [comment]
fitur MediaFirenya juga error' bang

**Comment by LitRHap** [comment]
iya sama down apinya

**Comment by LitRHap** [comment]
> fitur MediaFirenya juga error' bang

sama² down banh
